"""setup

Revision ID: 2c6e21cfcf3c
Revises: e4103987bb38
Create Date: 2025-02-08 16:00:05.049399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c6e21cfcf3c'
down_revision = 'e4103987bb38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('policy',
    sa.Column('excess', sa.Float(), nullable=False),
    sa.Column('premium', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('firstname', sa.String(length=80), nullable=True),
    sa.Column('surname', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('item',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('new_price', sa.Float(), nullable=True),
    sa.Column('fk_base_policy_id', sa.Integer(), nullable=True),
    sa.Column('fk_dao_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['fk_base_policy_id'], ['policy.id'], ),
    sa.ForeignKeyConstraint(['fk_dao_id'], ['dao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_in_committee',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dao_id'], ['dao.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'dao_id')
    )
    op.create_table('user_in_dao',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dao_id'], ['dao.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'dao_id')
    )
    op.create_table('claim',
    sa.Column('fk_user_id', sa.Integer(), nullable=False),
    sa.Column('fk_item_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=80), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['fk_item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['fk_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('insures',
    sa.Column('fk_user', sa.Integer(), nullable=False),
    sa.Column('fk_item', sa.Integer(), nullable=False),
    sa.Column('fk_policy', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fk_item'], ['item.id'], ),
    sa.ForeignKeyConstraint(['fk_policy'], ['policy.id'], ),
    sa.ForeignKeyConstraint(['fk_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('fk_user', 'fk_item', 'fk_policy')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('insures')
    op.drop_table('claim')
    op.drop_table('user_in_dao')
    op.drop_table('user_in_committee')
    op.drop_table('item')
    op.drop_table('user')
    op.drop_table('policy')
    op.drop_table('dao')
    # ### end Alembic commands ###
