"""updated dao table

Revision ID: ac802ff6f3ff
Revises: f66f425ac721
Create Date: 2025-02-08 23:26:09.201808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac802ff6f3ff'
down_revision = 'f66f425ac721'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('termination_period', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('joining_fee', sa.Numeric(), nullable=False))

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('premium_rate', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('premium_rate')

    with op.batch_alter_table('dao', schema=None) as batch_op:
        batch_op.drop_column('joining_fee')
        batch_op.drop_column('termination_period')

    # ### end Alembic commands ###
