"""empty message

Revision ID: f66f425ac721
Revises: 16b2a8875666
Create Date: 2025-02-08 19:03:51.374524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f66f425ac721'
down_revision = '16b2a8875666'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insure',
    sa.Column('fk_user_id', sa.Integer(), nullable=False),
    sa.Column('fk_item_id', sa.Integer(), nullable=False),
    sa.Column('fk_policy_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['fk_item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['fk_policy_id'], ['policy.id'], ),
    sa.ForeignKeyConstraint(['fk_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('insures')
    with op.batch_alter_table('dao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('money', sa.Numeric(), nullable=False))

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('excess_rate', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('excess_rate')

    with op.batch_alter_table('dao', schema=None) as batch_op:
        batch_op.drop_column('money')
        batch_op.drop_column('name')

    op.create_table('insures',
    sa.Column('fk_user', sa.INTEGER(), nullable=False),
    sa.Column('fk_item', sa.INTEGER(), nullable=False),
    sa.Column('fk_policy', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['fk_item'], ['item.id'], ),
    sa.ForeignKeyConstraint(['fk_policy'], ['policy.id'], ),
    sa.ForeignKeyConstraint(['fk_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('fk_user', 'fk_item', 'fk_policy')
    )
    op.drop_table('insure')
    # ### end Alembic commands ###
